dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  yamllint

platforms:
  - name: new-project-server
    box: ubuntu/bionic64
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8088"
provisioner:
  name: ansible
  lint: |
    ansible-lint
verifier:
  name: testinfra
  lint: |
    flake8